### PR TITLE
Add basic 64-bit support

### PR DESCRIPTION
**Pull request by linknum23**
This makes the installer work on a recent (bullseye) 64-bit pi

### CODE REVIEW

**Comment by linknum23** [comment]
This only fulfills part of #335 as it does not provide any migration. However this will allow us to start testing.

Before this is merged we will need to update the docs to explain what is necessary for a 64-bit setup. @Lohrer what modifications were needed for the bootstrapping script?

**Comment by Lohrer** [comment]
For Bullseye the biggest problem is the configure script fails to identify the platform as ARM. The current check is:
```python
if 'armv7l' in lplatform and 'debian' in lplatform
```

Buster x86 returned a string similar to `linux-5.10.103-v7+-armv7l-with-debian-10.13` for the platform name.
Bullseye x64 returns a string similar to `linux-5.15.76-v8+-aarch64-with-glibc2.31`

So there are two changes there, first 32-bit `armv7l` vs 64-bit `aarch64`. Second, `with-glibc` instead of `with-debian`.

The `bootstrap` branch also has a few tweaks and some work in progress on getting locale setup properly. We should also remove `piwiz` or otherwise disable it since it's sends an audible message until you complete the wizard in the GUI.

**Comment by rtertiaer** [comment]
@linknum23 can you reopen this? Github automagically closed it when I deleted `develop` :woozy_face: sorry!

**Comment by linknum23** [comment]
Looking at this again it is very like;y that these changes either no longer make sense or have been already incorporated. The only thing useful may be the builds of some 64-bit binaries.

**Pull request closed without merging**
