### PR TITLE
Update developer experience

### PR DESCRIPTION
**Pull request by linknum23**
- [x] Fix misc problems deploying from git bash
- [x] Update API documentation to be written for new users
- [x] Fix API server to use a relative URL
- [x] Fix failures in firmware flashing script
- [x] Document remote debugging with vscode @micronova-jb  I need help with this 
- [x] Add recommended extension hint for vscode
- [x] Document from scratch developer setup on windows
- [x] Edit DEVELOPING.md to reflect current workflows
- [x] Fixup deploy script to "just work"
- [x]  Add API endpoints for individual streams, sources, groups, zones, and presets lists

### CODE REVIEW

**Comment by linknum23** [comment]
@Lohrer Can you check out the updated documentation? I think its a lot more useful from the perspective of a new user. I realized I should just write it and have you check it out...

**Review by micronova-jb — APPROVED** [review]

**Comment by linknum23** [comment]
API Documentation is looking good, now we just need to figure out how to get the user/developer there.

**Comment by linknum23** [comment]
@mabowers can you try running the deploy script on git bash on windows and also on a mac terminal from a git checkout

**Comment by linknum23** [comment]
We will also need to document remote developing using vscode connected to the amplipi, I have a feeling many developers will do something like that.

**Comment by Lohrer** [comment]
Referencing Jeremy's "Remove VS Code Notes.docx":

- The remote SSH instructions are great!
- Put it in Markdown please
- I would recommend removing the windows 7 start menu in the screenshot on step 5, just show elements from VS Code iteself
- It's probably worth adding a link to the VS Code docs on this extension https://code.visualstudio.com/docs/remote/ssh
- Steps 9 and 10 (cloning a git repo through VS Code) aren't clear enough for me to follow. I've never used VS Code git.
- There are a couple minor wording changes I'd like to make once this is in markdown

**Comment by micronova-jb** [comment]
Thanks for the feedback! Yeah, the document was very quick and dirty, I
will definitely port it to markdown and clean it up significantly. Good to
know on the git thing, I'll go more in-depth when I update the document

**Pull request merged**
