### PR TITLE
CreateStreamShorten

### LINKED ISSUE #884: Create Stream Modal goes off page
image

Create stream modal is too tall, make max height lesser and include a scrollbar

### PR DESCRIPTION
**Pull request by SteveMicroNova**
### What does this change intend to accomplish?
Only some modals had scrollbars when necessary, add a scrollbar to the TypeSelect Modal and stylize all modal scrollbars
Closes #884 

### Checklist

* [x] Have you tested your changes and ensured they work?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] If applicable, have you updated the documentation/manual?
* [x] If applicable, have you updated the CHANGELOG?
* [ ] Does your submission pass linting & tests? You can test on localhost using `./scripts/test`
* [ ] Have you written new tests for your core features/changes, as applicable?
* [x] If this is a UI change, have you tested it across multiple browser platforms?
* [x] If this is a UI change, have you tested across multiple viewport sizes (ie. desktop versus mobile)?

### CODE REVIEW

**Comment by SteveMicroNova** [comment]
Before:
image

After:
image


Before:
image

After:
image

**Comment by klay2000** [comment]
please hide the scroll bar

**Review by klay2000 — CHANGES_REQUESTED** [review]
please hide the scroll bar

**Comment by SteveMicroNova** [comment]
https://github.com/user-attachments/assets/4bcc1085-9455-4cb9-8db4-c59464181204

**Comment by SteveMicroNova** [comment]
https://github.com/user-attachments/assets/c1086792-facf-4e7e-bd48-f0e47e2ac8d7

**Review by klay2000 — APPROVED** [review]
:scroll:

**Pull request merged**
