### PR TITLE
Remove desktop tests and make more configuration AmpliPi only

### PR DESCRIPTION
**Pull request by linknum23**
This cleans up some of our configuration script used to install development versions and updates on AmpliPis and development debian-based Linux machines.

- [x] Remove old (Desktop accessible) tests on an install
  - This may have some implications for our actual test setups if there are some uncommited tests.
  - A backup of tests should be made on those units. 
- [x] Add a simple tag to distinguish some of the things installed as amplipi-only?
  - This should avoid breaking development machines (Sorry @Lohrer!)
- [ ] Test this in conjunction with removing a test
- [x] Move the desktop icon creation into os-deps sub task

### CODE REVIEW

**Comment by linknum23** [comment]
Needs to be tested on a machine in the office to verify the logging fix is still applied.

**Comment by linknum23** [comment]
Hmm, lets see what we need to remove then!

**Comment by linknum23** [comment]
Whats left:
- [ ] test this in conjunction with removing a test
- [ ] move the desktop icon creation into os-deps sub task

**Comment by linknum23** [comment]
Updated to latest. Just needs a little testing.

**Comment by rtertiaer** [comment]
@linknum23  if you intend to ship this eventually, can you re-target this PR to `main`? Github automagically closed it when I deleted `develop` :woozy_face: sorry!

**Comment by linknum23** [comment]
Looking at this again, I cannot make a case for this being necessary in its current form.

**Pull request closed without merging**
